name: hot-shot-aviation
services:
- name: web
  source_dir: /
  github:
    repo: hotshotvny/hotshot-aviation-redesign
    branch: main
    deploy_on_push: true
  build_command: |
    npm ci
    npm run build
  run_command: node server.cjs
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  routes:
  - path: /
