name: hot-shot-aviation
static_sites:
- name: web
  source_dir: /
  github:
    repo: your-github-username/your-repo-name
    branch: main
    deploy_on_push: true
  build_command: |
    npm ci
    npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
  catchall_document: index.html