// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osfwukuxpangejponypj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZnd1a3V4cGFuZ2VqcG9ueXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNjI2NDAsImV4cCI6MjA3NjYzODY0MH0._Zlo7oTZzEZju4kn66K4ueCg5hF9e2sxvR1291B-o3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});