// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhpethvsqihowmozczij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJocGV0aHZzcWlob3dtb3pjemlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzM2NjIsImV4cCI6MjA3MjE0OTY2Mn0.fTMnC6q_n_-BCOsiNx7UhfTtTBdim_ahOOEHBWrbkNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});